apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: core
          image: eunjing/eunji:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
